app=test-configs
module=test-configs
report-interval=60000
service-count=1
service-prefix=test-configs
url=https://mulika.natujenge.ke/api/statistics/report-li
api-key=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwbXV0aXN5YUBtZWxpb3JhLnRlY2giLCJhdXRoIjoiUk9MRV9BUEkiLCJvaWQiOjIsIm90eXBlIjoiQ0xJRU5UIiwiZXhwIjoxOTAxNzgwNDQzfQ.2LdI9Rpu-tu4sN9h3KIGoq61ILdgvj7xQ9Dh_2L3Fei0VutF_JF7UIob5z_OKHV8XWFfW6P1aa0DB2gZH3_iow